#Dictionary matching full team names to their acronym
#Acronym used for scraping the basketball reference website
TEAM_NAME_ACRONYM = {
    "atlanta hawks":"ATL",
    "brooklyn nets":"BKN",
    "boston celtics":"BOS",
    "charlotte hornets":"CHA",
    "chicago bulls":"CHI",
    "cleveland cavaliers":"CLE",
    "dallas mavericks":"DAL",
    "denver nuggets":"DEN",
    "detroit pistons":"DET",
    "golden state warriors":"GSW",
    "houston rockets":"HOU",
    "indiana pacers":"IND",
    "los angeles clippers":"LAC",
    "los angeles lakers":"LAL",
    "memphis grizzlies":"MEM",
    "miami heat":"MIA",
    "milwaukee bucks":"MIL",
    "minnesota timberwolves":"MIN",
    "new orleans pelicans":"NOP",
    "new york knicks":"NYK",
    "oklahoma city thunder":"OKC",
    "orlando magic":"ORL",
    "philadelphia 76ers":"PHI",
    "phoenix suns":"PHX",
    "portland trail blazers":"POR",
    "sacramento kings":"SAC",
    "san antonio spurs":"SAS",
    "toronto raptors":"TOR",
    "utah jazz":"UTA",
    "washington wizards":"WAS"
}
